"""Add last_completed_date to user_activities

Revision ID: 0416e3dd955b
Revises: 
Create Date: 2025-04-06 01:20:35.735037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0416e3dd955b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activities', sa.Column('last_completed_date', sa.Date(), nullable=True))
    op.add_column('user_activities', sa.Column('has_freeze', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_activities', 'has_freeze')
    op.drop_column('user_activities', 'last_completed_date')
    # ### end Alembic commands ###
