"""Add referral relationship to User

Revision ID: 33f0cbed41e0
Revises: de60c4a76ae1
Create Date: 2025-04-06 14:06:27.530563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f0cbed41e0'
down_revision: Union[str, None] = 'de60c4a76ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_activities', 'streak',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_activities', 'streak_frozen',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_activities', 'has_freeze',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'users', ['referred_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('user_activities', 'has_freeze',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_activities', 'streak_frozen',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_activities', 'streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
