"""Modified has_freeze in user_activities

Revision ID: de60c4a76ae1
Revises: 0416e3dd955b
Create Date: 2025-04-06 02:44:37.956851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de60c4a76ae1'
down_revision: Union[str, None] = '0416e3dd955b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_activities', 'streak',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_activities', 'streak_frozen',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_activities', 'has_freeze',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_activities', 'has_freeze',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_activities', 'streak_frozen',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_activities', 'streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
